name: divi-dashboard-dev

services:
  api:
    container_name: divi_api
    restart: unless-stopped
    build:
      context: ./apps/middleware
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PASS: ${PG_DB_PASS}
      PG_DB: ${PG_DB}
      PG_DB_HOST: db
      PG_DB_PORT: 5432
      ENVIRONMENT: ${ENVIRONMENT:-Development}
    volumes:
      - ./apps/middleware:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    container_name: divi_postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASS}
      POSTGRES_DB: ${PG_DB}
      ENVIRONMENT: ${ENVIRONMENT:-Development}
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data_v1:/var/lib/postgresql/data

  web:
    container_name: divi_web
    restart: unless-stopped
    user: '${UID:-1000}:${GID:-1000}'
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '5174:5174'
    environment:
      CHOKIDAR_USEPOLLING: true
      ENVIRONMENT: ${ENVIRONMENT:-Development}
    command: npm run start:web:dev

  storybook:
    container_name: divi_dux
    restart: unless-stopped
    user: '${UID:-1000}:${GID:-1000}'
    build:
      context: .
      dockerfile: ./packages/divi-docs/Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '5175:5175'
    depends_on:
      - web
    environment:
      CHOKIDAR_USEPOLLING: true
      ENVIRONMENT: ${ENVIRONMENT:-Development}
      CI: 'true'
    command: npm run start:docs:dev

volumes:
  postgres_data_v1:
