extend:
  - dir: ./src/Components/
    friendlyName: Add Unit Test file
    nameCase: pascal
    structure:
      - type: folder
        name: tests
        content:
          - type: file
            suffix: .test
            extension: tsx
            content:
              src: ./../../.common/templates/tests/component.test.tsx

  - dir: ./src/Components/
    friendlyName: Add Visual Test file
    nameCase: pascal
    structure:
      - type: folder
        name: tests
        content:
          - type: file
            suffix: .spec
            extension: ts
            content:
              src: ./../../.common/templates/tests/component.spec.tsx

create:
  - dest: ./src/Components/
    friendlyName: Full Split - ForwardRef Component
    nameCase: pascal
    structure:
      - type: file
        name: index
        extension: ts
        content:
          src: ./../../.common/templates/forwardRef/index.component.ts

      - type: file
        extension: ts
        content:
          src: ./../../.common/templates/forwardRef/component.ts

      - type: file
        suffix: .types
        extension: ts
        content:
          src: ./../../.common/templates/forwardRef/component.types.ts

      - type: file
        suffix: .styles
        extension: ts
        prefix: use
        content:
          src: ./../../.common/templates/forwardRef/component.use.styles.ts

      - type: file
        extension: tsx
        prefix: use
        content:
          src: ./../../.common/templates/forwardRef/component.use.ts

      - type: file
        extension: tsx
        prefix: render
        content:
          src: ./../../.common/templates/forwardRef/component.render.tsx

      - type: folder
        name: stories
        content:
          - type: file
            name: index
            extension: ts
            content:
              src: ./../../.common/templates/stories/index.stories.ts

          - type: file
            suffix: .stories
            extension: tsx
            content:
              src: ./../../.common/templates/stories/component.stories.tsx

      
      - type: folder
        name: tests
        content:
          - type: file
            name: index
            extension: ts
            content:
              src: ./../../.common/templates/tests/index.tests.ts
          
          - type: file
            suffix: .test
            extension: tsx
            content:
              src: ./../../.common/templates/tests/component.test.tsx
              
          - type: file
            suffix: .spec
            extension: tsx
            content:
              src: ./../../.common/templates/tests/component.spec.tsx
